name: rd
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.7
  - bcftools=1.11
  - pysam=0.16.0.1
  - pandas=1.2.1
  - bwa=0.7.17
  - samtools=1.11
  - bamtools=2.5.1
  - parallel=20190522
  - bedtools=2.29
  - sed=4.7
  - snakemake-wrapper-utils=0.1.3
  - gatk4=4.1.9.0
  - picard=2.25.0
